/*
 * The MIT License
 *
 * Copyright 2022 Mastfrog Technologies.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.telenav.smithy.java.generators.builtin.struct.impl;

import com.telenav.smithy.java.generators.builtin.struct.DocumentationContributor;
import com.telenav.smithy.java.generators.builtin.struct.StructureGenerationHelper;
import com.telenav.smithy.java.generators.builtin.struct.StructureGenerator;
import static com.telenav.smithy.java.generators.builtin.struct.impl.DefaultStructureGenerators.MAVEN_ARTIFACT_ID;
import static com.telenav.smithy.java.generators.builtin.struct.impl.DefaultStructureGenerators.MAVEN_GROUP_ID;
import com.mastfrog.util.libversion.VersionInfo;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import software.amazon.smithy.model.shapes.StructureShape;

/**
 *
 * @author Tim Boudreau
 */
final class GeneratedFromClassDocs implements DocumentationContributor<StructureShape, StructureGenerationHelper> {

    private final Class<?> generatorType;

    GeneratedFromClassDocs(Class<?> type) {
        generatorType = type;
    }

    GeneratedFromClassDocs() {
        this(StructureGenerator.class);
    }

    @Override
    public void generateDocumentation(StructureGenerationHelper target, StringBuilder docHead, StringBuilder docTail) {
        docTail.append("<p><b>Generated By:</b> <i> ").append(generatorType.getSimpleName());
        VersionInfo vi = VersionInfo.find(Registry.class, MAVEN_GROUP_ID, MAVEN_ARTIFACT_ID);
        if (vi != null) {
            if (vi.foundMavenMetadata) {
                docTail.append(" in <b>").append(vi.groupId).append(':').append(vi.artifactId).append(" version ").append(vi.version).append("</b>");
            }
            if (vi.foundGitMetadata) {
                // It is important, for repeatable builds, that the time zone
                // does not vary depending on the machine it is built on, or the
                // doc jar, at the least, will differ.
                docTail.append(" commit date ").append(vi.commitDate.withZoneSameInstant(ZoneId.of("Z")).format(DateTimeFormatter.RFC_1123_DATE_TIME)).append(" commit ").append(vi.shortCommitHash);
                if (vi.dirty) {
                    docTail.append(" <u>dirty</u>");
                }
            }
            docTail.append("</i>");
        }
    }

}
